### ISSUE TITLE
Logo & Banners

### ISSUE THREAD

**Issue by mubaidr** [mubaidr/bulma-pro#1]
@jbeguna04 please

**Comment by jbeguna04** [comment]
Hello @mubaidr , what can i help about this project?

**Comment by mubaidr** [comment]
This is css library same as `bulma-fluent`, demo here: https://mubaidr.js.org/bulma-pro/#/

If possible can you create just one icon for this?

**Comment by jbeguna04** [comment]
I try to make some proposals @mubaidr , Thanks for trusting me this.

**Comment by jbeguna04** [comment]
Good Day @mubaidr , Do have any preferred color for the logo ?

**Comment by mubaidr** [comment]
Looks very good! Awesome work!

No preference for color, just try color you think will suit it best.

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/47476798-af9db180-d854-11e8-824f-53cf90c7d16f.png)

Here are some color choices:

**Comment by mubaidr** [comment]
Can you use this color? (this is one of color used in the theme)
```
#009dcc
```

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/47479365-7caceb00-d85f-11e8-91a0-369e5305fd72.png)

**Comment by mubaidr** [comment]
Awesome! Good to go!

Please create pull-request.

**Comment by jbeguna04** [comment]
OKay sir , I will. Thank you for your cooperation

**Comment by mubaidr** [comment]
Thanks @jbeguna04 https://github.com/mubaidr/bulma-pro/pull/2/files
